# Generated by Django 5.0.2 on 2024-03-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('fullname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('r', 'renter'), ('o', 'owner')], max_length=1)),
            ],
        ),
    ]
