# Generated by Django 5.0.3 on 2024-03-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='SL_No',
            new_name='ST_No',
        ),
    ]
