# Generated by Django 5.0.3 on 2024-03-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_api', '0002_rename_sl_no_property_st_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Availability',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Bathrooms',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Rooms',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Building_No',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ST_No',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Type',
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('villa', 'Villa')], default='house', max_length=50),
        ),
    ]
